g1 = raw_input("Enter grade 1: ")
grade1 = float(g1)
g2 = raw_input("Enter grade 2: ")
grade2 = float(g2)
g3 = raw_input("Enter grade 3: ")
grade3 = float(g3)
g4 = raw_input("Enter grade 4: ")
grade4 = float(g4)
g5 = raw_input("Enter grade 5: ")
grade5 = float(g5)
average = (grade1 + grade2 + grade3 + grade4 + grade5) / 5
print("The average of the 5 grades is " + str(average))
